# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  go: circleci/go@1.7.1

jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - go/install
      - go/test:
          coverprofile: cover-source.out 

workflows:
  example-workflow:
    jobs:
      - test