# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  go: circleci/go@1.7.1

jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - go/install
      - checkout
      - run:
          name: Setup Code Climate test-reporter
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      - go/test:
          coverprofile: c.out 
      - run:
          name: Report code coverage
          command: ./cc-test-reporter after-build --coverage-input-type gocov --exit-code $?

workflows:
  example-workflow:
    jobs:
      - test